openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test Project
  description: "Test Project"

paths:
  /rest:
    get:
      tags:
        - TEST
      operationId: getRest
      responses:
        200:
          description: All OK
          content:
            application/json:
              schema:
                type: string
